application:
  version: 4.0
spring:
  data:
    mongodb:
      authentication-database: admin
#      uri: mongodb://188.227.18.141/lib
      host: 188.227.18.141
      port: 27017
      database: lib
      #      url: jdbc:postgresql://188.227.18.141:5432/lib_spring_data
      username: temp_user
      password: temp_pas
#  shell:
#    interactive:
#      enabled: true

#      driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        temp:
#          use_jdbc_metadata_defaults: false
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    hibernate:
#      ddl-auto: update